'use strict'

// Import necessary libraries
const crypto = require('crypto');

// Define constants
const DOCUMENT_SCHEMA_VERSION = '1.0';
const DOCUMENT_SCHEMA_TYPE = 'data/abstraction/document';
const DOCUMENT_DATA_CHECKSUM_ALGO = 'sha1';
const DOCUMENT_DATA_FORMAT = 'application/json';
const DOCUMENT_DATA_ENCODING = 'utf8';

// TODO: Add data index fields

// Document class
class Document {

    constructor({
        id = null,
        type = DOCUMENT_SCHEMA_TYPE,
        schemaVersion = DOCUMENT_SCHEMA_VERSION,
        version = 0,
        meta = {},
        data = null,
        dataChecksumFields = [],
        dataChecksumAlgorithm = DOCUMENT_DATA_CHECKSUM_ALGO,
        dataIndexFields = []
    }) {

        this.id = id;
        this.type = type;
        this.schemaVersion = schemaVersion;

        // Set meta information
        const now = new Date().toISOString();
        this.meta = {
            created: meta.created || now,
            modified: now,
            contentType: DOCUMENT_DATA_FORMAT,
            contentEncoding: DOCUMENT_DATA_ENCODING,
            ...meta
        };

        // Document data
        this.data = data;

        // Generate checksum
        let dataChecksum = this.calculateChecksum(dataChecksumFields, data);
        this.checksum = `${dataChecksumAlgorithm}/${dataChecksum}`

        // Set version information
        this.version = version;
    }

    toJSON() {
        return {
            // Mandatory parameters
            schemaVersion: this.schemaVersion,

            id: this.id,
            type: this.type,
            version: this.version,

            checksum: this.checksum,
            dataChecksumAlgorithm: this.dataChecksumAlgorithm,

            // Optional parameters (will be autogenerated if missing)
            meta: this.meta,
            data: this.data,
            versions: this.versions
        }
    }

    static toJSON() {
        return {
            // Mandatory parameters
            schemaVersion: DOCUMENT_SCHEMA_VERSION,
            dataChecksumAlgorithm: DOCUMENT_DATA_CHECKSUM_ALGO,
            id: null,
            type: DOCUMENT_SCHEMA_TYPE,
            version: 1,
            checksum: null,

            // Optional parameters (will be autogenerated if missing)
            meta: {},
            data: {},
            versions: []
        }
    }

    static fromJSON(json) {
        // TODO: Fix for "undefined"
        let document = new Document({
            schemaVersion: json.schemaVersion,
            id: json.id,
            type: json.type,
            checksum: json.checksum,
            meta: json.meta,
            data: json.data,
            versions: json.versions
        })

        return document;
    }

    calculateChecksum(fields = this.dataChecksumFields, data = this.data) {
        const checksumData = fields.length ? fields.reduce((acc, field) => {
            acc[field] = data[field];
            return acc;
        }, {}) : data;

        return this.createHash(checksumData);
    }

    createHash(str, algorithm = DOCUMENT_DATA_CHECKSUM_ALGO, encoding = DOCUMENT_DATA_ENCODING) {
        if (typeof str === 'object') str = JSON.stringify(str)
        return crypto
            .createHash(algorithm)
            .update(str, encoding)
            .digest('hex')
    }

    static createHash(str, algorithm = DOCUMENT_DATA_CHECKSUM_ALGO, encoding = DOCUMENT_DATA_ENCODING) {
        if (typeof str === 'object') str = JSON.stringify(str)
        return crypto
            .createHash(algorithm)
            .update(str, encoding)
            .digest('hex')
    }

    // TODO: Should replace the toJSON and fromJSON methods
    serialize() {
        return JSON.stringify(this);
    }

    // TODO: Should replace the toJSON and fromJSON methods
    static deserialize(data) {
        const obj = JSON.parse(data);
        return new Document(obj);
    }

    validate() {
        if (!this.type) throw new Error('Document type is not defined')
        if (!this.data) throw new Error('Document data is not defined')
        return true;
    }

    static validate(document) {
        if (!document) throw new Error('Document is not defined')

        // Check for mandatory parameters (TODO)
        return (
            document.type &&
            document.data
        ) || false
    }

    get schema() { return this.toJSON(); }
    static get schema() { return Document.toJSON(); }

    static get schemaVersion() {
        return DOCUMENT_SCHEMA_VERSION;
    }

    get schemaType() { return this.type; }
    static get schemaType() {
        return DOCUMENT_SCHEMA_TYPE;
    }
}

module.exports = Document
